# Generated by Django 3.0.3 on 2020-02-11 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('redditclone', '0002_tread_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mpttcomment',
            name='tread',
        ),
    ]
