# Generated by Django 3.0.3 on 2020-02-12 18:23

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('redditclone', '0003_remove_mpttcomment_tread'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpttcomment',
            name='votes',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mpttcomment',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='redditclone.MPTTComment'),
        ),
    ]
